package Vista;

import java.awt.Color;
import java.awt.Font;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.ScrollPaneConstants;

public class VentanaAgregarCongelado extends JFrame {
	JButton Comprar;
	JLabel nombre;
	JTextField nombre_;
	JLabel temperatura;
	JLabel grados;
	JComboBox<String> temperatura_;
	JLabel FechaCaducidad;
	JComboBox<String> diaca;
	JComboBox<String> mesca;
	JComboBox<String> añoca;
	JLabel NumeroDeLote;
	JTextField NumeroDeLote_;
	JLabel FechaEnvasado;
	JComboBox<String> diaen;
	JComboBox<String> mesen;
	JComboBox<String> añoen;
	JLabel PaisOrigen;
	JTextField paisOrigen_;

	public VentanaAgregarCongelado() {
		setTitle("AGREGAR PRODUCTO CONGELADO");
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		getContentPane().setLayout(null);
		setResizable(false);
		getContentPane().setBackground(Color.white);
		setBounds(0, 0, 300, 300);
		setLocationRelativeTo(null);
		this.setBackground(Color.white);

		JPanel AgregarCongelado = new JPanel();
		setLayout(null);
		nombre = new JLabel("NOMBRE PRODUCTO:");
		nombre_ = new JTextField(100);
		PaisOrigen = new JLabel("PAIS ORIGEN:");
		paisOrigen_ = new JTextField(100);
		NumeroDeLote = new JLabel("NUMERO DE LOTE:");
		NumeroDeLote_ = new JTextField(100);
		temperatura = new JLabel("TEMPERATURA:");
		grados = new JLabel("GRADOS");
		temperatura_ = new JComboBox<String>();
		temperatura_.addItem("-30");
		temperatura_.addItem("-29");
		temperatura_.addItem("-28");
		temperatura_.addItem("-27");
		temperatura_.addItem("-26");
		temperatura_.addItem("-25");
		temperatura_.addItem("-24");
		temperatura_.addItem("-23");
		temperatura_.addItem("-22");
		temperatura_.addItem("-21");
		temperatura_.addItem("-20");
		temperatura_.addItem("-19");
		temperatura_.addItem("-18");
		temperatura_.addItem("-17");
		temperatura_.addItem("-16");
		temperatura_.addItem("-15");
		temperatura_.addItem("-14");
		temperatura_.addItem("-13");
		temperatura_.addItem("-12");
		temperatura_.addItem("-11");
		temperatura_.addItem("-10");
		temperatura_.addItem("-9");
		temperatura_.addItem("-8");
		temperatura_.addItem("-7");
		temperatura_.addItem("-6");
		temperatura_.addItem("-5");
		temperatura_.addItem("-4");
		temperatura_.addItem("-3");
		temperatura_.addItem("-2");
		temperatura_.addItem("-1");
		temperatura_.addItem("0");
		temperatura_.addItem("1");
		temperatura_.addItem("2");
		temperatura_.addItem("3");
		temperatura_.addItem("4");
		temperatura_.addItem("5");
		temperatura_.addItem("6");
		temperatura_.addItem("7");
		temperatura_.addItem("8");
		temperatura_.addItem("9");
		temperatura_.addItem("10");
		temperatura_.addItem("11");
		temperatura_.addItem("12");
		temperatura_.addItem("13");
		temperatura_.addItem("14");
		temperatura_.addItem("15");
		temperatura_.addItem("16");
		temperatura_.addItem("17");
		temperatura_.addItem("18");
		temperatura_.addItem("19");
		temperatura_.addItem("20");
		temperatura_.addItem("21");
		temperatura_.addItem("22");
		temperatura_.addItem("23");
		temperatura_.addItem("24");
		temperatura_.addItem("25");
		temperatura_.addItem("26");
		temperatura_.addItem("27");
		temperatura_.addItem("28");
		temperatura_.addItem("29");
		temperatura_.addItem("30");
		FechaEnvasado = new JLabel("FECHA ENVASADO:");
		diaen = new JComboBox<String>();
		diaen.addItem("1");
		diaen.addItem("2");
		diaen.addItem("3");
		diaen.addItem("4");
		diaen.addItem("5");
		diaen.addItem("6");
		diaen.addItem("7");
		diaen.addItem("8");
		diaen.addItem("9");
		diaen.addItem("10");
		diaen.addItem("11");
		diaen.addItem("12");
		diaen.addItem("13");
		diaen.addItem("14");
		diaen.addItem("15");
		diaen.addItem("16");
		diaen.addItem("17");
		diaen.addItem("18");
		diaen.addItem("19");
		diaen.addItem("20");
		diaen.addItem("21");
		diaen.addItem("22");
		diaen.addItem("23");
		diaen.addItem("24");
		diaen.addItem("25");
		diaen.addItem("26");
		diaen.addItem("27");
		diaen.addItem("28");
		diaen.addItem("29");
		diaen.addItem("30");
		diaen.addItem("31");
		mesen = new JComboBox<String>();
		mesen.addItem("Enero");
		mesen.addItem("Febrero");
		mesen.addItem("Marzo");
		mesen.addItem("Abril");
		mesen.addItem("Mayo");
		mesen.addItem("Junio");
		mesen.addItem("Julio");
		mesen.addItem("Agosto");
		mesen.addItem("Septiembre");
		mesen.addItem("Octubre");
		mesen.addItem("Noviembre");
		mesen.addItem("Diciembre");
		añoen = new JComboBox<String>();
		añoen.addItem("2001");
		añoen.addItem("2002");
		añoen.addItem("2003");
		añoen.addItem("2004");
		añoen.addItem("2005");
		añoen.addItem("2006");
		añoen.addItem("2007");
		añoen.addItem("2008");
		añoen.addItem("2009");
		añoen.addItem("2010");
		añoen.addItem("2011");
		añoen.addItem("2012");
		añoen.addItem("2013");
		añoen.addItem("2014");
		añoen.addItem("2015");
		añoen.addItem("2016");
		añoen.addItem("2017");
		añoen.addItem("2018");
		añoen.addItem("2019");
		FechaCaducidad = new JLabel();
		diaca = new JComboBox<String>();
		diaca.addItem("1");
		diaca.addItem("2");
		diaca.addItem("3");
		diaca.addItem("4");
		diaca.addItem("5");
		diaca.addItem("6");
		diaca.addItem("7");
		diaca.addItem("8");
		diaca.addItem("9");
		diaca.addItem("10");
		diaca.addItem("11");
		diaca.addItem("12");
		diaca.addItem("13");
		diaca.addItem("14");
		diaca.addItem("15");
		diaca.addItem("16");
		diaca.addItem("17");
		diaca.addItem("18");
		diaca.addItem("19");
		diaca.addItem("20");
		diaca.addItem("21");
		diaca.addItem("22");
		diaca.addItem("23");
		diaca.addItem("24");
		diaca.addItem("25");
		diaca.addItem("26");
		diaca.addItem("27");
		diaca.addItem("28");
		diaca.addItem("29");
		diaca.addItem("30");
		diaca.addItem("31");
		mesca = new JComboBox<String>();
		mesca.addItem("Enero");
		mesca.addItem("Febrero");
		mesca.addItem("Marzo");
		mesca.addItem("Abril");
		mesca.addItem("Mayo");
		mesca.addItem("Junio");
		mesca.addItem("Julio");
		mesca.addItem("Agosto");
		mesca.addItem("Septiembre");
		mesca.addItem("Octubre");
		mesca.addItem("Noviembre");
		mesca.addItem("Diciembre");
		añoca = new JComboBox<String>();
		añoca.addItem("2019");
		añoca.addItem("2020");
		añoca.addItem("2021");
		añoca.addItem("2022");
		añoca.addItem("2023");
		añoca.addItem("2024");
		añoca.addItem("2025");
		setVisible(false);
	}
}
